// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef MainWindowUI_h
#define MainWindowUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "StatusTable.h"
#include <FL/Fl_Box.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include "TableEditor.h"
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Menu_Bar.H>
#include "LogView.h"
#include <FL/Fl_Button.H>
#include "OutputEditor.h"
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Tree.H>
#include "LogViewEditor.h"

class MainWindowUI {
public:
  MainWindowUI();
protected:
  Fl_Double_Window *m_main_window;
  StatusTable *m_status_table;
public:
  Fl_Box *m_connection_status;
protected:
  Fl_Output *m_rate;
  Fl_Progress *m_interrogation_progress;
  Fl_Group *m_table_editor_box;
  Fl_Input *m_table_title;
  TableEditor *m_table_editor;
  Fl_Spinner *m_table_rows;
  Fl_Spinner *m_table_cols;
  Fl_Check_Button *m_tracing;
  Fl_Scroll *m_sensor_editor_box;
  Fl_Choice *m_sensor_source;
  Fl_Choice *m_sensor_method;
  Fl_Value_Input *m_sensor_pin;
  Fl_Value_Input *m_sensor_lag;
  Fl_Value_Input *m_sensor_range_min;
  Fl_Value_Input *m_sensor_range_max;
  Fl_Value_Input *m_sensor_therm_bias;
  Fl_Value_Input *m_sensor_therm_A;
  Fl_Value_Input *m_sensor_therm_B;
  Fl_Value_Input *m_sensor_therm_C;
  Fl_Value_Input *m_sensor_window_width;
  Fl_Value_Input *m_sensor_window_total;
  Fl_Value_Input *m_sensor_window_offset;
  Fl_Value_Input *m_sensor_fault_min;
  Fl_Value_Input *m_sensor_fault_max;
  Fl_Value_Input *m_sensor_fault_value;
  Fl_Value_Input *m_sensor_const;
public:
  Fl_Menu_Bar *m_bar;
  static Fl_Menu_Item menu_m_bar[];
protected:
  static Fl_Menu_Item *m_file_menu;
public:
  static Fl_Menu_Item *m_file_open;
protected:
  static Fl_Menu_Item *m_file_loadconfig;
public:
  static Fl_Menu_Item *m_file_export;
  static Fl_Menu_Item *m_file_import;
protected:
  static Fl_Menu_Item *m_target_menu;
public:
  static Fl_Menu_Item *m_target_flash;
  static Fl_Menu_Item *m_target_bootloader;
protected:
  static Fl_Menu_Item *m_connection_menu;
public:
  static Fl_Menu_Item *m_connection_device;
  static Fl_Menu_Item *m_connection_simulator;
  static Fl_Menu_Item *m_connection_offline;
protected:
  Fl_Output *m_status_text;
  LogView *m_logview;
  Fl_Output *m_offline;
public:
  Fl_Button *m_logview_follow;
protected:
  Fl_Group *m_output_editor_box;
  OutputEditor *m_output_editor;
public:
  Fl_Button *m_logview_forward;
  Fl_Button *m_logview_pause;
  Fl_Button *m_logview_back;
  Fl_Button *m_logview_in;
  Fl_Button *m_logview_out;
protected:
  Fl_Tree *m_config_tree;
public:
  LogViewEditor *m_logview_editor;
  void show();
};
#endif
