// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef MainWindowUI_h
#define MainWindowUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tree.H>
#include "StatusTable.h"
#include <FL/Fl_Box.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Table.H>

class MainWindowUI {
public:
  MainWindowUI();
protected:
  Fl_Double_Window *m_main_window;
  Fl_Tree *m_config_tree;
  StatusTable *m_status_table;
public:
  Fl_Box *m_connection_status;
protected:
  Fl_Output *m_rate;
  Fl_Progress *m_interrogation_progress;
  Fl_Group *m_table_editor_box;
  Fl_Input *m_table_title;
  Fl_Table *m_table_editor;
  Fl_Group *m_sensor_editor_box;
  Fl_Input *m_sensor_pin;
public:
  void show();
};
#endif
